FROM debian:8

# Zabbix agent build prerequisites
RUN apt-get update && apt-get install -y build-essential devscripts quilt
RUN apt-get install -y git autoconf autoconf automake wget unzip gcc pkg-config

# Required for Zabbix tarball compiling
RUN apt-get install -y ruby rubygems
RUN gem install sass --version '=3.4.22'

# Required by packaging that builds Zabbix server and proxy in addition to the agent
RUN apt-get install -y libsnmp-dev libmysqlclient-dev libpq-dev libsqlite3-dev libcurl4-openssl-dev libldap2-dev libiksemel-dev libopenipmi-dev libssh2-1-dev unixodbc-dev openjdk-7-jdk libxml2-dev

# Additional dependencies by Zabbix version 3.4
RUN apt-get install -y libpcre++-dev libevent-dev

# Build script
WORKDIR /build
COPY build.sh /build.sh
RUN chmod a+x /build.sh
CMD ["/bin/bash", "/build.sh"]
ENV ZABBIX_VERSION=3.4.4
ENV ZABBIX_BRANCH=pulssi-$ZABBIX_VERSION
ENV PULSSI_RELEASE_VERSION=2
ENV URL_ZABBIX_DSC http://repo.zabbix.com/zabbix/3.4/debian/pool/main/z/zabbix/zabbix_3.4.4-4+jessie.dsc
